export class productDB {
  static product = [
    {
      productId: 1,
      img: 'assets/images/electronics/product/1.jpg',
      product_title: 'Slim Fit Cotton Shirt',
      discount: '$500.00',
      price: '$600.00',
      sale: 'not on sale',
      tag: 'old',
    },
    {
      productId: 2,
      img: 'assets/images/electronics/product/1.jpg',
      product_title: 'Slim Fit Cotton Shirt',
      discount: '$500.00',
      price: '$600.00',
      sale: 'not on sale',
      tag: 'old',
    },
    {
      productId: 3,
      img: 'assets/images/electronics/product/1.jpg',
      product_title: 'Slim Fit Cotton Shirt',
      discount: '$500.00',
      price: '$600.00',
      sale: 'on sale',
      tag: 'new',
    },
    {
      productId: 4,
      img: 'assets/images/electronics/product/1.jpg',
      product_title: 'Slim Fit Cotton Shirt',
      discount: '$500.00',
      price: '$600.00',
      sale: 'not on sale',
      tag: 'old',
    },
    {
      productId: 5,
      img: 'assets/images/electronics/product/1.jpg',
      product_title: 'Slim Fit Cotton Shirt',
      discount: '$500.00',
      price: '$600.00',
      sale: 'not on sale',
      tag: 'old',
    },
    {
      productId: 6,
      img: 'assets/images/electronics/product/1.jpg',
      product_title: 'Slim Fit Cotton Shirt',
      discount: '$500.00',
      price: '$600.00',
      sale: 'not on sale',
      tag: 'old',
    },
    {
      productId: 7,
      img: 'assets/images/electronics/product/1.jpg',
      product_title: 'Slim Fit Cotton Shirt',
      discount: '$500.00',
      price: '$600.00',
      sale: 'not on sale',
      tag: 'old',
    },
    {
      productId: 8,
      img: 'assets/images/electronics/product/1.jpg',
      product_title: 'Slim Fit Cotton Shirt',
      discount: '$500.00',
      price: '$600.00',
      sale: 'not on sale',
      tag: 'old',
    },
  ];
}
